### ISSUE TITLE
expectXmlNodes diff in tests is too verbose

### ISSUE THREAD

**Issue by kasbah** [tracespace/pcb-stackup-core#6]
The diff is worse than useless unfortunately because it forces you to scroll up loads to find out which test failed. It's not really easy to see what the difference between expected and result is. Would be nice to reduce it down to just the info required.

**Comment by mcous** [comment]
Unfortunately the length of the failed expectation is a function of sinon + sinon-chai. Also unfortunately, I've had to use these extremely long diffs to catch bugs while refactoring. But yeah, it gets onerous.

Perhaps we can check out a different stubbing / expectation library? I've been really enjoying using [testdouble.js](https://github.com/testdouble/testdouble.js) for stubbing, and generally I'm trying to move away from chai to just good old fashioned [assert](https://nodejs.org/api/assert.html).

That being said, maybe all we need to do is rework how [expectXmlNodes](https://github.com/tracespace/pcb-stackup-core/blob/master/test/expect-xml-nodes.js) works to somehow not compare the expected call to every single call to the spy.
