### ISSUE TITLE
Drop Node v0.10 support

### ISSUE THREAD

**Issue by mcous** [tracespace/pcb-stackup-core#7]
Node v0.10 has been EOL'd.

- [ ] Set Travis config
    - Test v4 LTS, v6 LTS, and latest
    - Clean up build matrix to avoid duplicating the Node tests for the browser tests
    - See this build config: https://github.com/mcous/gonogo/blob/master/.travis.yml
- [x] Update blocked dependencies
    - ESLint can be updated to latest
    - Maybe just use [standard](https://github.com/feross/standard)?

**Comment by kasbah** [comment]
Do you want to get this done before we do a release?

**Comment by mcous** [comment]
Yeah if we're doing a major bump it's probably a good idea to roll this in
here. Then again it's not super pressing

**Comment by kasbah** [comment]
I sent PRs for 'standard' and updating the deps but I don't fully understand what's needed on the Travis stuff. I'd like to get a realease out, upgrade pcb-stackup to it so I can use the new Inkscape niceness for PNGs on Kitnic without messing about with branch versions.

**Comment by kasbah** [comment]
Closed with #9, excluding the Travis stuff.

**Comment by mcous** [comment]
I'm gonna leave this issue open for the Travis stuff, just because I don't want to give the impression (via the Travis config) that we "officially" support 0.10 anymore. I know the necessary changes so I can take care of it

**Comment by kasbah** [comment]
Haha, you asked me to close it! :laughing:

**Comment by mcous** [comment]
Oh man, my bad. I'm an idiot and (I think I) meant to ask if #8 could be closed via #9. Womp womp.

**Comment by mcous** [comment]
Closed by tracespace/tracespace#59
